server:
  port: 8081

#urls
url:
  factoria: /api/averia/exists/{idFactoria}/{idMaquina}
  equipos:


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka
#    serviceUrl.defaultZone: http://client-registry:8761/eureka

spring:
  main:
    banner-mode: off
  application:
    name: gestorIncidencias

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
