server:
  port: 8082

equipos: equipo1, equipo2, equipo3, equipo4


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka
#    serviceUrl.defaultZone: http://client-registry:8761/eureka

spring:
  main:
    banner-mode: off
  application:
    name: asignacion

