server:
  port: 8080

spring:
  main:
    banner-mode: off
  application:
    name: factoria

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queue:
  name: appExchange